services:
    app.serializer:
            class: JMS\Serializer\SerializerBuilder

    app.parser:
        class: AppBundle\Service\ParserService
        arguments: ['@doctrine.orm.entity_manager', '@app.serializer']